[package]
name = "pixelpipe-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
pixelpipe-core = { path = "../pixelpipe-core" }
pixelpipe-project = { path = "../pixelpipe-project" }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[lints]
workspace = true
