[package]
name = "pixelate-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "pixelate"
path = "src/main.rs"

[dependencies]
clap.workspace = true
pixelate-app = { path = "../pixelate-app" }
pixelate-core = { path = "../pixelate-core" }
pixelate-project = { path = "../pixelate-project" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
png.workspace = true
tempfile = "3"

[lints]
workspace = true
